# Generated by Django 4.2.17 on 2025-09-16 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscriber",
        ),
    ]
