# Generated by Django 5.0.8 on 2026-01-08 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_course_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="overview",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="WhatStudentWillLearn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.TextField(
                        help_text="Describe what the student will learn in this course"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_outcomes",
                        to="course.course",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
