# Generated by Django 5.0.8 on 2025-12-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
