# Generated by Django 5.0.8 on 2026-01-08 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profession_qualification_facilitatorprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facilitatorprofile",
            name="profession",
        ),
        migrations.RemoveField(
            model_name="facilitatorprofile",
            name="qualifications",
        ),
        migrations.AddField(
            model_name="profession",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facilitator_proffession",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="qualification",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facilitator_qualification",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
