# Generated by Django 5.0.8 on 2026-01-08 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_facilitatorprofile_profession_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profession",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facilitator_profession",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
