# Generated by Django 5.1.8 on 2025-09-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_subscriber"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUsRecipients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
