# Generated by Django 5.0.8 on 2026-01-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseenrollment",
            name="enrolled_at",
        ),
        migrations.AddField(
            model_name="courseenrollment",
            name="has_completed",
            field=models.BooleanField(default=False),
        ),
    ]
