# Generated by Django 5.1.8 on 2025-08-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facebook_onboarding", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboardedclient",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="onboardedclient",
            name="business_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="onboardedclient",
            name="last_seen",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="onboardedclient",
            name="meta",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="onboardedclient",
            name="phone_number_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="onboardedclient",
            name="access_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="onboardedclient",
            name="whatsapp_business_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
